// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PostOfficeShipment.Infrastructure.Data;

#nullable disable

namespace PostOfficeShipment.Infrastructure.Migrations
{
    [DbContext(typeof(ShipmentDbContext))]
    [Migration("20260828172635_SeedPostOffices")]
    partial class SeedPostOffices
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PostOfficeShipment.Domain.Entities.PostOffice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("ZipCode")
                        .IsUnique();

                    b.ToTable("PostOffices", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Connaught Place, New Delhi",
                            CreatedAt = new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "New Delhi Central",
                            UpdatedAt = new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            ZipCode = "110001"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Sector 18, Noida",
                            CreatedAt = new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Noida Central",
                            UpdatedAt = new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            ZipCode = "201301"
                        },
                        new
                        {
                            Id = 3,
                            Address = "MG Road, Gurugram",
                            CreatedAt = new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Gurugram Central",
                            UpdatedAt = new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            ZipCode = "122001"
                        });
                });

            modelBuilder.Entity("PostOfficeShipment.Domain.Entities.Shipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentPostOfficeId")
                        .HasColumnType("integer");

                    b.Property<int>("DestinationPostOfficeId")
                        .HasColumnType("integer");

                    b.Property<int>("OriginPostOfficeId")
                        .HasColumnType("integer");

                    b.Property<string>("ShipmentNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ShipmentType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Weight")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)");

                    b.HasKey("Id");

                    b.HasIndex("CurrentPostOfficeId");

                    b.HasIndex("DestinationPostOfficeId");

                    b.HasIndex("OriginPostOfficeId");

                    b.HasIndex("ShipmentNumber")
                        .IsUnique();

                    b.ToTable("Shipments", (string)null);

                    b.HasDiscriminator<string>("ShipmentType").HasValue("Shipment");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("PostOfficeShipment.Domain.Entities.ShipmentStatusHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PostOfficeId")
                        .HasColumnType("integer");

                    b.Property<int>("ShipmentId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PostOfficeId");

                    b.HasIndex("ShipmentId", "ChangedAt");

                    b.ToTable("ShipmentStatusHistory", (string)null);
                });

            modelBuilder.Entity("PostOfficeShipment.Domain.Entities.Letter", b =>
                {
                    b.HasBaseType("PostOfficeShipment.Domain.Entities.Shipment");

                    b.HasDiscriminator().HasValue("Letter");
                });

            modelBuilder.Entity("PostOfficeShipment.Domain.Entities.Package", b =>
                {
                    b.HasBaseType("PostOfficeShipment.Domain.Entities.Shipment");

                    b.HasDiscriminator().HasValue("Package");
                });

            modelBuilder.Entity("PostOfficeShipment.Domain.Entities.Shipment", b =>
                {
                    b.HasOne("PostOfficeShipment.Domain.Entities.PostOffice", "CurrentPostOffice")
                        .WithMany("CurrentShipments")
                        .HasForeignKey("CurrentPostOfficeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PostOfficeShipment.Domain.Entities.PostOffice", "DestinationPostOffice")
                        .WithMany("DestinationShipments")
                        .HasForeignKey("DestinationPostOfficeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PostOfficeShipment.Domain.Entities.PostOffice", "OriginPostOffice")
                        .WithMany("OriginShipments")
                        .HasForeignKey("OriginPostOfficeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CurrentPostOffice");

                    b.Navigation("DestinationPostOffice");

                    b.Navigation("OriginPostOffice");
                });

            modelBuilder.Entity("PostOfficeShipment.Domain.Entities.ShipmentStatusHistory", b =>
                {
                    b.HasOne("PostOfficeShipment.Domain.Entities.PostOffice", "PostOffice")
                        .WithMany("ShipmentStatusHistories")
                        .HasForeignKey("PostOfficeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PostOfficeShipment.Domain.Entities.Shipment", "Shipment")
                        .WithMany("StatusHistory")
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PostOffice");

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("PostOfficeShipment.Domain.Entities.PostOffice", b =>
                {
                    b.Navigation("CurrentShipments");

                    b.Navigation("DestinationShipments");

                    b.Navigation("OriginShipments");

                    b.Navigation("ShipmentStatusHistories");
                });

            modelBuilder.Entity("PostOfficeShipment.Domain.Entities.Shipment", b =>
                {
                    b.Navigation("StatusHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
